export const MOCK_EVENTS = [
  {
    id: "1",
    title: "Tech Conference 2025",
    description: "Join industry leaders for a day of innovation and networking",
    fullDescription:
      "Experience the future of technology at our annual conference. Featuring keynote speakers from leading tech companies, interactive workshops, and networking sessions. Perfect for entrepreneurs, developers, and tech enthusiasts looking to stay ahead of the curve.",
    date: "2025-03-15",
    time: "09:00 AM",
    endTime: "05:00 PM",
    location: "San Francisco, CA",
    venue: "Moscone Center, 747 Howard St",
    price: 199,
    image: "/placeholder.svg?height=400&width=800",
    category: "Conference",
    attendees: 1250,
    ticketsAvailable: 850,
  },
  {
    id: "2",
    title: "Summer Music Festival",
    description: "Three days of live music from your favorite artists",
    fullDescription:
      "Celebrate summer with three days of non-stop music featuring top artists across multiple genres. Multiple stages, food vendors, and camping available. Don't miss this year's hottest music event.",
    date: "2025-06-21",
    time: "02:00 PM",
    endTime: "11:00 PM",
    location: "Los Angeles, CA",
    venue: "Hollywood Park Grounds, Los Angeles, CA",
    price: 89,
    image: "/placeholder.svg?height=400&width=800",
    category: "Festival",
    attendees: 8500,
    ticketsAvailable: 2100,
  },
  {
    id: "3",
    title: "Startup Pitch Night",
    description: "Watch emerging startups pitch their ideas to venture capitalists",
    fullDescription:
      "Join us for an evening of entrepreneurship as selected startups present their innovative solutions to leading venture capitalists. Great networking opportunity for investors and founders.",
    date: "2025-04-10",
    time: "06:00 PM",
    endTime: "08:30 PM",
    location: "New York, NY",
    venue: "WeWork Hudson Yards, 410 Tenth Ave",
    price: 45,
    image: "/placeholder.svg?height=400&width=800",
    category: "Networking",
    attendees: 350,
    ticketsAvailable: 180,
  },
  {
    id: "4",
    title: "Art Exhibition Opening",
    description: "Experience contemporary art from emerging artists worldwide",
    fullDescription:
      "Celebrate contemporary art at our annual opening gala. Features work from emerging artists across continents. Wine and refreshments included.",
    date: "2025-05-03",
    time: "07:00 PM",
    endTime: "10:00 PM",
    location: "New York, NY",
    venue: "The Modern Museum of Art, 11 W 53rd St",
    price: 25,
    image: "/placeholder.svg?height=400&width=800",
    category: "Art",
    attendees: 600,
    ticketsAvailable: 400,
  },
  {
    id: "5",
    title: "Professional Development Workshop",
    description: "Upskill with hands-on training in the latest technologies",
    fullDescription:
      "Full-day intensive workshop covering cutting-edge technologies and best practices. Lunch and materials included. Limited to 50 participants for hands-on training.",
    date: "2025-02-20",
    time: "10:00 AM",
    endTime: "04:00 PM",
    location: "Chicago, IL",
    venue: "Chicago Tech Hub, 333 W Wacker Dr",
    price: 129,
    image: "/placeholder.svg?height=400&width=800",
    category: "Workshop",
    attendees: 200,
    ticketsAvailable: 50,
  },
  {
    id: "6",
    title: "Annual Charity Gala",
    description: "Evening of elegance supporting local education initiatives",
    fullDescription:
      "Join us for an evening of sophistication and giving. Gourmet dinner, live entertainment, and silent auction. All proceeds benefit local education programs.",
    date: "2025-04-25",
    time: "07:30 PM",
    endTime: "11:00 PM",
    location: "Boston, MA",
    venue: "The Four Seasons Hotel Boston, 200 Boylston St",
    price: 250,
    image: "/placeholder.svg?height=400&width=800",
    category: "Gala",
    attendees: 400,
    ticketsAvailable: 200,
  },
]
