export const MOCK_ARTISTS = [
  {
    id: "artist-1",
    name: "Alex Chen",
    role: "Keynote Speaker",
    image: "/placeholder.svg?height=400&width=400",
    banner: "/placeholder.svg?height=300&width=1200",
    description:
      "CEO of TechCorp, pioneer in AI and machine learning. Alex has delivered keynotes at over 50 international conferences and is passionate about making technology accessible to everyone.",
    genre: "Technology",
    followers: 5700,
    verified: true,
    socialLinks: {
      twitter: "https://twitter.com",
      linkedin: "https://linkedin.com",
      youtube: "https://youtube.com",
    },
  },
  {
    id: "artist-2",
    name: "Sarah Williams",
    role: "Workshop Host",
    image: "/placeholder.svg?height=400&width=400",
    banner: "/placeholder.svg?height=300&width=1200",
    description:
      "Full-stack developer and open-source advocate with 10+ years of industry experience. Sarah specializes in web development and mentoring the next generation of developers.",
    genre: "Education",
    followers: 3200,
    verified: true,
    socialLinks: {
      twitter: "https://twitter.com",
      github: "https://github.com",
    },
  },
]

export const MOCK_VENUES = {
  "1": {
    id: "venue-1",
    name: "Moscone Center",
    address: "747 Howard St",
    city: "San Francisco, CA",
    capacity: 3000,
    amenities: ["WiFi", "Catering", "Parking", "Restrooms", "Accessibility"],
    description: "Premier convention center with multiple halls and modern facilities",
  },
  "2": {
    id: "venue-2",
    name: "Hollywood Park Grounds",
    address: "1050 S Prairie Ave",
    city: "Los Angeles, CA",
    capacity: 50000,
    amenities: ["Camping", "Food Courts", "Multiple Stages", "VIP Areas", "Medical Station"],
    description: "Large outdoor festival grounds with capacity for major music events",
  },
  "3": {
    id: "venue-3",
    name: "WeWork Hudson Yards",
    address: "410 Tenth Ave",
    city: "New York, NY",
    capacity: 500,
    amenities: ["WiFi", "Projectors", "Sound System", "Catering", "Breakout Rooms"],
    description: "Modern coworking space ideal for networking events",
  },
  "4": {
    id: "venue-4",
    name: "The Modern Museum of Art",
    address: "11 W 53rd St",
    city: "New York, NY",
    capacity: 800,
    amenities: ["Gallery Space", "Wine Bar", "Restrooms", "Climate Control"],
    description: "Prestigious art museum with beautiful gallery spaces",
  },
  "5": {
    id: "venue-5",
    name: "Chicago Tech Hub",
    address: "333 W Wacker Dr",
    city: "Chicago, IL",
    capacity: 200,
    amenities: ["WiFi", "A/V Equipment", "Kitchenette", "Parking", "Accessibility"],
    description: "State-of-the-art technology center for workshops and training",
  },
  "6": {
    id: "venue-6",
    name: "The Four Seasons Hotel Boston",
    address: "200 Boylston St",
    city: "Boston, MA",
    capacity: 1000,
    amenities: ["Luxury Dining", "Ballroom", "Bar Service", "Valet Parking", "Accessibility"],
    description: "Five-star hotel with elegant ballroom and premium catering",
  },
}

export const MOCK_EVENTS = [
  {
    id: "1",
    title: "Tech Conference 2025",
    description: "Join industry leaders for a day of innovation and networking",
    fullDescription:
      "Experience the future of technology at our annual conference. Featuring keynote speakers from leading tech companies, interactive workshops, and networking sessions. Perfect for entrepreneurs, developers, and tech enthusiasts looking to stay ahead of the curve.",
    date: "2025-03-15",
    time: "09:00 AM",
    endTime: "05:00 PM",
    location: "San Francisco, CA",
    venue: "Moscone Center, 747 Howard St",
    venueDetails: MOCK_VENUES["1"],
    artists: MOCK_ARTISTS,
    price: 199,
    image: "/placeholder.svg?height=400&width=800",
    category: "Conference",
    attendees: 1250,
    ticketsAvailable: 850,
  },
  {
    id: "2",
    title: "Summer Music Festival",
    description: "Three days of live music from your favorite artists",
    fullDescription:
      "Celebrate summer with three days of non-stop music featuring top artists across multiple genres. Multiple stages, food vendors, and camping available. Don't miss this year's hottest music event.",
    date: "2025-06-21",
    time: "02:00 PM",
    endTime: "11:00 PM",
    location: "Los Angeles, CA",
    venue: "Hollywood Park Grounds, Los Angeles, CA",
    venueDetails: MOCK_VENUES["2"],
    price: 89,
    image: "/placeholder.svg?height=400&width=800",
    category: "Festival",
    attendees: 8500,
    ticketsAvailable: 2100,
  },
  {
    id: "3",
    title: "Startup Pitch Night",
    description: "Watch emerging startups pitch their ideas to venture capitalists",
    fullDescription:
      "Join us for an evening of entrepreneurship as selected startups present their innovative solutions to leading venture capitalists. Great networking opportunity for investors and founders.",
    date: "2025-04-10",
    time: "06:00 PM",
    endTime: "08:30 PM",
    location: "New York, NY",
    venue: "WeWork Hudson Yards, 410 Tenth Ave",
    venueDetails: MOCK_VENUES["3"],
    price: 45,
    image: "/placeholder.svg?height=400&width=800",
    category: "Networking",
    attendees: 350,
    ticketsAvailable: 180,
  },
  {
    id: "4",
    title: "Art Exhibition Opening",
    description: "Experience contemporary art from emerging artists worldwide",
    fullDescription:
      "Celebrate contemporary art at our annual opening gala. Features work from emerging artists across continents. Wine and refreshments included.",
    date: "2025-05-03",
    time: "07:00 PM",
    endTime: "10:00 PM",
    location: "New York, NY",
    venue: "The Modern Museum of Art, 11 W 53rd St",
    venueDetails: MOCK_VENUES["4"],
    price: 25,
    image: "/placeholder.svg?height=400&width=800",
    category: "Art",
    attendees: 600,
    ticketsAvailable: 400,
  },
  {
    id: "5",
    title: "Professional Development Workshop",
    description: "Upskill with hands-on training in the latest technologies",
    fullDescription:
      "Full-day intensive workshop covering cutting-edge technologies and best practices. Lunch and materials included. Limited to 50 participants for hands-on training.",
    date: "2025-02-20",
    time: "10:00 AM",
    endTime: "04:00 PM",
    location: "Chicago, IL",
    venue: "Chicago Tech Hub, 333 W Wacker Dr",
    venueDetails: MOCK_VENUES["5"],
    price: 129,
    image: "/placeholder.svg?height=400&width=800",
    category: "Workshop",
    attendees: 200,
    ticketsAvailable: 50,
  },
  {
    id: "6",
    title: "Annual Charity Gala",
    description: "Evening of elegance supporting local education initiatives",
    fullDescription:
      "Join us for an evening of sophistication and giving. Gourmet dinner, live entertainment, and silent auction. All proceeds benefit local education programs.",
    date: "2025-04-25",
    time: "07:30 PM",
    endTime: "11:00 PM",
    location: "Boston, MA",
    venue: "The Four Seasons Hotel Boston, 200 Boylston St",
    venueDetails: MOCK_VENUES["6"],
    price: 250,
    image: "/placeholder.svg?height=400&width=800",
    category: "Gala",
    attendees: 400,
    ticketsAvailable: 200,
  },
]
