export type AdminResourceFieldType = "text" | "number" | "select" | "datetime" | "boolean" | "uuid" | "json" | "readonly"

export type AdminResourceField = {
  name: string
  label: string
  type: AdminResourceFieldType
  required?: boolean
  readonly?: boolean
  options?: string[]
  placeholder?: string
}

export type AdminResource = {
  key: string
  label: string
  table: string
  primaryKey: string
  description: string
  orderBy: string
  fields: AdminResourceField[]
  listColumns: string[]
}

const idField: AdminResourceField = { name: "id", label: "ID", type: "readonly", readonly: true }
const createdAtField: AdminResourceField = { name: "created_at", label: "Created At", type: "readonly", readonly: true }

export const ADMIN_RESOURCES: AdminResource[] = [
  {
    key: "organizations",
    label: "Organizations",
    table: "organizations",
    primaryKey: "id",
    description: "Create and manage organizer/company accounts.",
    orderBy: "created_at",
    listColumns: ["name", "slug", "created_at"],
    fields: [idField, { name: "name", label: "Name", type: "text", required: true }, { name: "slug", label: "Slug", type: "text", required: true, placeholder: "new-life-entertainment" }, { name: "bio", label: "Bio", type: "text" }, { name: "logo", label: "Logo URL", type: "text" }],
  },
  {
    key: "org-members",
    label: "Org Members",
    table: "org_members",
    primaryKey: "user_id",
    description: "Assign organizer owners, admins, staff and finance users.",
    orderBy: "created_at",
    listColumns: ["org_id", "user_id", "role", "created_at"],
    fields: [{ name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "user_id", label: "User ID", type: "uuid", required: true }, { name: "role", label: "Role", type: "select", options: ["organizer_owner", "organizer_admin", "organizer_staff", "finance", "organizer_scanner"], required: true }, createdAtField],
  },
  {
    key: "venues",
    label: "Venues",
    table: "venues",
    primaryKey: "id",
    description: "Manage event venues and their city/capacity metadata.",
    orderBy: "created_at",
    listColumns: ["name", "city", "capacity"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "name", label: "Name", type: "text", required: true }, { name: "slug", label: "Slug", type: "text", required: true }, { name: "address", label: "Address", type: "text" }, { name: "city", label: "City", type: "text" }, { name: "tz", label: "Timezone", type: "text", placeholder: "Africa/Mbabane" }, { name: "capacity", label: "Capacity", type: "number" }],
  },
  {
    key: "artists",
    label: "Artists",
    table: "artists",
    primaryKey: "id",
    description: "Manage artists, speakers and performers linked to events.",
    orderBy: "created_at",
    listColumns: ["name", "slug", "created_at"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "name", label: "Name", type: "text", required: true }, { name: "slug", label: "Slug", type: "text", required: true }, { name: "bio", label: "Bio", type: "text" }, { name: "primary_user_id", label: "Primary User ID", type: "uuid" }, { name: "image_url", label: "Image URL", type: "text" }],
  },
  {
    key: "events",
    label: "Events",
    table: "events",
    primaryKey: "id",
    description: "Publish, archive and update marketplace events.",
    orderBy: "created_at",
    listColumns: ["title", "status", "city", "starts_at"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "venue_id", label: "Venue ID", type: "uuid", required: true }, { name: "title", label: "Title", type: "text", required: true }, { name: "slug", label: "Slug", type: "text", required: true }, { name: "status", label: "Status", type: "select", options: ["draft", "published", "archived"], required: true }, { name: "visibility", label: "Visibility", type: "select", options: ["public", "unlisted", "private"], required: true }, { name: "category", label: "Category", type: "text" }, { name: "city", label: "City", type: "text" }, { name: "country_code", label: "Country Code", type: "text", placeholder: "SZ" }, { name: "starts_at", label: "Starts At", type: "datetime" }, { name: "ends_at", label: "Ends At", type: "datetime" }, { name: "cover_image_url", label: "Cover Image URL", type: "text" }, { name: "description", label: "Description", type: "text" }],
  },
  {
    key: "event-dates",
    label: "Event Dates",
    table: "event_dates",
    primaryKey: "id",
    description: "Manage multi-date or repeated event instances.",
    orderBy: "created_at",
    listColumns: ["event_id", "starts_at", "ends_at"],
    fields: [idField, { name: "event_id", label: "Event ID", type: "uuid", required: true }, { name: "starts_at", label: "Starts At", type: "datetime", required: true }, { name: "ends_at", label: "Ends At", type: "datetime", required: true }],
  },
  {
    key: "event-artists",
    label: "Event Artists",
    table: "event_artists",
    primaryKey: "event_id",
    description: "Link artists and performers to events.",
    orderBy: "event_id",
    listColumns: ["event_id", "artist_id", "role"],
    fields: [{ name: "event_id", label: "Event ID", type: "uuid", required: true }, { name: "artist_id", label: "Artist ID", type: "uuid", required: true }, { name: "role", label: "Role", type: "text" }],
  },
  {
    key: "ticket-types",
    label: "Ticket Types",
    table: "ticket_types",
    primaryKey: "id",
    description: "Control ticket tiers, quotas and prices.",
    orderBy: "created_at",
    listColumns: ["name", "price_cents", "currency", "quota"],
    fields: [idField, { name: "event_id", label: "Event ID", type: "uuid", required: true }, { name: "name", label: "Name", type: "text", required: true }, { name: "price_cents", label: "Price (cents)", type: "number", required: true }, { name: "currency", label: "Currency", type: "text", required: true, placeholder: "SZL" }, { name: "quota", label: "Quota", type: "number", required: true }, { name: "per_user_limit", label: "Per User Limit", type: "number" }, { name: "is_reserved_seating", label: "Reserved Seating", type: "boolean" }],
  },
  {
    key: "ticket-type-channels",
    label: "Ticket Type Channels",
    table: "ticket_type_channels",
    primaryKey: "ticket_type_id",
    description: "Control channel-specific ticket quotas and purchase limits.",
    orderBy: "ticket_type_id",
    listColumns: ["ticket_type_id", "channel", "quota", "per_order_limit"],
    fields: [{ name: "ticket_type_id", label: "Ticket Type ID", type: "uuid", required: true }, { name: "channel", label: "Channel", type: "select", options: ["online", "pos", "reseller", "import"], required: true }, { name: "quota", label: "Quota", type: "number" }, { name: "per_order_limit", label: "Per Order Limit", type: "number" }],
  },
  {
    key: "seat-maps",
    label: "Seat Maps",
    table: "seat_maps",
    primaryKey: "id",
    description: "Store reserved seating map schemas per event.",
    orderBy: "created_at",
    listColumns: ["event_id", "created_at"],
    fields: [idField, { name: "event_id", label: "Event ID", type: "uuid", required: true }, { name: "schema", label: "Seat Map JSON", type: "json", required: true }],
  },
  {
    key: "seats",
    label: "Seats",
    table: "seats",
    primaryKey: "id",
    description: "Manage individual seats within a seat map.",
    orderBy: "created_at",
    listColumns: ["seat_map_id", "label", "created_at"],
    fields: [idField, { name: "seat_map_id", label: "Seat Map ID", type: "uuid", required: true }, { name: "label", label: "Seat Label", type: "text", required: true }],
  },
  {
    key: "seat-holds",
    label: "Seat Holds",
    table: "seat_holds",
    primaryKey: "id",
    description: "Monitor temporary seat or quantity reservations.",
    orderBy: "created_at",
    listColumns: ["event_id", "status", "quantity", "expires_at"],
    fields: [idField, { name: "event_id", label: "Event ID", type: "uuid", required: true }, { name: "ticket_type_id", label: "Ticket Type ID", type: "uuid" }, { name: "hold_code", label: "Hold Code", type: "text" }, { name: "status", label: "Status", type: "select", options: ["active", "released", "expired"], required: true }, { name: "quantity", label: "Quantity", type: "number", required: true }, { name: "expires_at", label: "Expires At", type: "datetime" }, { name: "created_by", label: "Created By", type: "uuid" }],
  },
  {
    key: "guestlist-entries",
    label: "Guestlist Entries",
    table: "guestlist_entries",
    primaryKey: "id",
    description: "Manage complimentary and guest access lists.",
    orderBy: "created_at",
    listColumns: ["full_name", "email", "phone", "allocation"],
    fields: [idField, { name: "event_id", label: "Event ID", type: "uuid", required: true }, { name: "ticket_type_id", label: "Ticket Type ID", type: "uuid" }, { name: "full_name", label: "Full Name", type: "text", required: true }, { name: "email", label: "Email", type: "text" }, { name: "phone", label: "Phone", type: "text" }, { name: "allocation", label: "Allocation", type: "number", required: true }, { name: "notes", label: "Notes", type: "text" }],
  },
  {
    key: "orders",
    label: "Orders",
    table: "orders",
    primaryKey: "id",
    description: "Review and update checkout/order state.",
    orderBy: "created_at",
    listColumns: ["status", "total_cents", "currency", "created_at"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "buyer_id", label: "Buyer ID", type: "uuid", required: true }, { name: "status", label: "Status", type: "select", options: ["pending", "paid", "failed", "refunded"], required: true }, { name: "total_cents", label: "Total (cents)", type: "number", required: true }, { name: "currency", label: "Currency", type: "text", required: true }, { name: "channel", label: "Channel", type: "select", options: ["online", "pos", "reseller", "import"] }, { name: "buyer_email", label: "Buyer Email", type: "text" }, { name: "buyer_phone", label: "Buyer Phone", type: "text" }],
  },
  {
    key: "order-items",
    label: "Order Items",
    table: "order_items",
    primaryKey: "id",
    description: "Manage issued tickets, ticket codes, holders and check-in state.",
    orderBy: "created_at",
    listColumns: ["ticket_code", "status", "holder_name", "checked_in_at"],
    fields: [idField, { name: "order_id", label: "Order ID", type: "uuid", required: true }, { name: "ticket_type_id", label: "Ticket Type ID", type: "uuid", required: true }, { name: "seat_id", label: "Seat ID", type: "uuid" }, { name: "ticket_code", label: "Ticket Code", type: "text", required: true }, { name: "status", label: "Status", type: "select", options: ["pending", "issued", "transferred", "checked_in", "revoked", "refunded"], required: true }, { name: "holder_name", label: "Holder Name", type: "text" }, { name: "holder_email", label: "Holder Email", type: "text" }, { name: "holder_phone", label: "Holder Phone", type: "text" }, { name: "checked_in_at", label: "Checked In At", type: "datetime" }, { name: "revoked_at", label: "Revoked At", type: "datetime" }, { name: "refunded_at", label: "Refunded At", type: "datetime" }],
  },
  {
    key: "payments",
    label: "Payments",
    table: "payments",
    primaryKey: "id",
    description: "Review provider payment records and payment state.",
    orderBy: "created_at",
    listColumns: ["provider", "status", "amount_cents", "currency"],
    fields: [idField, { name: "order_id", label: "Order ID", type: "uuid", required: true }, { name: "provider", label: "Provider", type: "text", required: true }, { name: "amount_cents", label: "Amount (cents)", type: "number", required: true }, { name: "currency", label: "Currency", type: "text", required: true }, { name: "ext_payment_id", label: "External Payment ID", type: "text" }, { name: "status", label: "Status", type: "select", options: ["succeeded", "failed", "pending", "refunded"] }, { name: "channel", label: "Channel", type: "select", options: ["online", "pos", "reseller", "import"] }, { name: "payload", label: "Payload JSON", type: "json" }],
  },
  {
    key: "payment-attempts",
    label: "Payment Attempts",
    table: "payment_attempts",
    primaryKey: "id",
    description: "Track payment initialization and verification attempts.",
    orderBy: "created_at",
    listColumns: ["provider", "attempt_no", "status", "created_at"],
    fields: [idField, { name: "order_id", label: "Order ID", type: "uuid", required: true }, { name: "provider", label: "Provider", type: "text", required: true }, { name: "attempt_no", label: "Attempt No", type: "number", required: true }, { name: "status", label: "Status", type: "select", options: ["pending", "succeeded", "failed", "timed_out", "cancelled"], required: true }, { name: "ext_ref", label: "External Ref", type: "text" }, { name: "payment_id", label: "Payment ID", type: "uuid" }, { name: "payload", label: "Payload JSON", type: "json" }],
  },
  {
    key: "payouts",
    label: "Payouts",
    table: "payouts",
    primaryKey: "id",
    description: "Manage payout status and settlement references.",
    orderBy: "created_at",
    listColumns: ["status", "amount_cents", "currency", "provider"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "amount_cents", label: "Amount (cents)", type: "number", required: true }, { name: "currency", label: "Currency", type: "text", required: true }, { name: "provider", label: "Provider", type: "text", required: true }, { name: "destination_ref", label: "Destination Ref", type: "text" }, { name: "status", label: "Status", type: "select", options: ["requested", "processing", "paid", "failed", "cancelled"], required: true }, { name: "paid_at", label: "Paid At", type: "datetime" }],
  },
  {
    key: "payout-accounts",
    label: "Payout Accounts",
    table: "payout_accounts",
    primaryKey: "id",
    description: "Manage organizer payout provider references.",
    orderBy: "created_at",
    listColumns: ["org_id", "provider", "created_at"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "provider", label: "Provider", type: "text", required: true }, { name: "details_encrypted", label: "Encrypted Details", type: "text", required: true }],
  },
  {
    key: "refunds",
    label: "Refunds",
    table: "refunds",
    primaryKey: "id",
    description: "Review refund requests and processing state.",
    orderBy: "created_at",
    listColumns: ["status", "amount_cents", "currency", "type"],
    fields: [idField, { name: "payment_id", label: "Payment ID", type: "uuid", required: true }, { name: "amount_cents", label: "Amount (cents)", type: "number", required: true }, { name: "currency", label: "Currency", type: "text", required: true }, { name: "type", label: "Type", type: "select", options: ["full", "partial"], required: true }, { name: "status", label: "Status", type: "select", options: ["requested", "processing", "processed", "failed", "cancelled"], required: true }, { name: "provider_ref", label: "Provider Ref", type: "text" }, { name: "initiated_by", label: "Initiated By", type: "uuid" }, { name: "processed_at", label: "Processed At", type: "datetime" }, { name: "provider_payload", label: "Provider Payload", type: "json" }],
  },
  {
    key: "refund-items",
    label: "Refund Items",
    table: "refund_items",
    primaryKey: "id",
    description: "Track item-level refund allocations.",
    orderBy: "created_at",
    listColumns: ["refund_id", "amount_cents", "currency", "reason"],
    fields: [idField, { name: "refund_id", label: "Refund ID", type: "uuid", required: true }, { name: "order_item_id", label: "Order Item ID", type: "uuid" }, { name: "amount_cents", label: "Amount (cents)", type: "number", required: true }, { name: "currency", label: "Currency", type: "text", required: true }, { name: "reason", label: "Reason", type: "text" }, { name: "user_id", label: "User ID", type: "uuid" }],
  },
  {
    key: "ledger-entries",
    label: "Ledger Entries",
    table: "ledger_entries",
    primaryKey: "id",
    description: "Internal accounting entries for orders, payments, refunds and payouts.",
    orderBy: "occurred_at",
    listColumns: ["type", "amount_cents", "currency", "occurred_at"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "event_id", label: "Event ID", type: "uuid" }, { name: "order_id", label: "Order ID", type: "uuid" }, { name: "payment_id", label: "Payment ID", type: "uuid" }, { name: "refund_id", label: "Refund ID", type: "uuid" }, { name: "payout_id", label: "Payout ID", type: "uuid" }, { name: "type", label: "Type", type: "select", options: ["order_gross", "fee", "tax", "discount", "payment_net", "refund", "payout"], required: true }, { name: "amount_cents", label: "Amount (cents)", type: "number", required: true }, { name: "currency", label: "Currency", type: "text", required: true }, { name: "meta", label: "Meta JSON", type: "json" }],
  },
  {
    key: "pricing-plans",
    label: "Pricing Plans",
    table: "pricing_plans",
    primaryKey: "id",
    description: "Configure platform and processor fee rules per organization.",
    orderBy: "created_at",
    listColumns: ["org_id", "platform_percent_bps", "platform_fixed_cents", "active"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "platform_percent_bps", label: "Platform Percent BPS", type: "number", required: true }, { name: "platform_fixed_cents", label: "Platform Fixed Cents", type: "number", required: true }, { name: "processor_percent_bps", label: "Processor Percent BPS", type: "number", required: true }, { name: "processor_fixed_cents", label: "Processor Fixed Cents", type: "number", required: true }, { name: "platform_fee_payer", label: "Platform Fee Payer", type: "select", options: ["buyer", "organizer"], required: true }, { name: "processor_fee_payer", label: "Processor Fee Payer", type: "select", options: ["buyer", "organizer"], required: true }, { name: "currency", label: "Currency", type: "text", required: true }, { name: "active", label: "Active", type: "boolean" }],
  },
  {
    key: "transfers",
    label: "Transfers",
    table: "transfers",
    primaryKey: "id",
    description: "Monitor peer-to-peer ticket transfer requests.",
    orderBy: "created_at",
    listColumns: ["status", "from_user_id", "to_user_id", "created_at"],
    fields: [idField, { name: "order_item_id", label: "Order Item ID", type: "uuid" }, { name: "from_user_id", label: "From User ID", type: "uuid" }, { name: "to_user_id", label: "To User ID", type: "uuid" }, { name: "status", label: "Status", type: "select", options: ["requested", "pending", "accepted", "declined", "cancelled", "completed"], required: true }, { name: "metadata", label: "Metadata JSON", type: "json" }],
  },
  {
    key: "resale-listings",
    label: "Resale Listings",
    table: "resale_listings",
    primaryKey: "id",
    description: "Monitor paid marketplace ticket resale listings.",
    orderBy: "created_at",
    listColumns: ["status", "price_cents", "currency", "listing_expires_at"],
    fields: [idField, { name: "order_item_id", label: "Order Item ID", type: "uuid", required: true }, { name: "seller_id", label: "Seller ID", type: "uuid", required: true }, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "price_cents", label: "Price (cents)", type: "number", required: true }, { name: "currency", label: "Currency", type: "text", required: true }, { name: "status", label: "Status", type: "select", options: ["active", "sold", "cancelled", "expired"], required: true }, { name: "listing_expires_at", label: "Listing Expires At", type: "datetime" }, { name: "transfer_fee_cents", label: "Transfer Fee Cents", type: "number" }, { name: "transfer_id", label: "Transfer ID", type: "uuid" }, { name: "metadata", label: "Metadata JSON", type: "json" }],
  },
  {
    key: "waitlists",
    label: "Waitlists",
    table: "waitlists",
    primaryKey: "id",
    description: "Review users waiting for sold-out ticket types.",
    orderBy: "created_at",
    listColumns: ["event_id", "ticket_type_id", "user_id", "created_at"],
    fields: [idField, { name: "event_id", label: "Event ID", type: "uuid", required: true }, { name: "ticket_type_id", label: "Ticket Type ID", type: "uuid", required: true }, { name: "user_id", label: "User ID", type: "uuid", required: true }],
  },
  {
    key: "event-staff",
    label: "Event Staff",
    table: "event_staff",
    primaryKey: "user_id",
    description: "Manage event-level staff and scanner roles.",
    orderBy: "created_at",
    listColumns: ["event_id", "user_id", "role", "active"],
    fields: [{ name: "event_id", label: "Event ID", type: "uuid", required: true }, { name: "user_id", label: "User ID", type: "uuid", required: true }, { name: "role", label: "Role", type: "select", options: ["organizer_admin", "organizer_staff", "scanner"], required: true }, { name: "active", label: "Active", type: "boolean" }],
  },
  {
    key: "devices",
    label: "Devices",
    table: "devices",
    primaryKey: "id",
    description: "Manage POS, scanner and kiosk devices.",
    orderBy: "created_at",
    listColumns: ["label", "device_role", "last_seen_at", "event_id"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "event_id", label: "Event ID", type: "uuid" }, { name: "registered_by", label: "Registered By", type: "uuid" }, { name: "label", label: "Label", type: "text" }, { name: "device_role", label: "Device Role", type: "select", options: ["organizer_pos", "organizer_scanner", "organizer_kiosk", "scanner_unassigned"], required: true }, { name: "max_scans_per_minute", label: "Max Scans Per Minute", type: "number" }, { name: "last_seen_at", label: "Last Seen At", type: "datetime" }],
  },
  {
    key: "device-sessions",
    label: "Device Sessions",
    table: "device_sessions",
    primaryKey: "id",
    description: "Track scanner/POS device user sessions.",
    orderBy: "started_at",
    listColumns: ["device_id", "user_id", "started_at", "ended_at"],
    fields: [idField, { name: "device_id", label: "Device ID", type: "uuid", required: true }, { name: "user_id", label: "User ID", type: "uuid" }, { name: "started_at", label: "Started At", type: "datetime" }, { name: "ended_at", label: "Ended At", type: "datetime" }],
  },
  {
    key: "scans",
    label: "Scans",
    table: "scans",
    primaryKey: "id",
    description: "Review ticket scan outcomes and venue entry events.",
    orderBy: "scanned_at",
    listColumns: ["ticket_code", "outcome", "scanned_at", "gate"],
    fields: [idField, { name: "event_id", label: "Event ID", type: "uuid", required: true }, { name: "order_item_id", label: "Order Item ID", type: "uuid" }, { name: "ticket_code", label: "Ticket Code", type: "text", required: true }, { name: "outcome", label: "Outcome", type: "select", options: ["valid", "already_used", "revoked", "invalid", "wrong_event"], required: true }, { name: "device_id", label: "Device ID", type: "uuid" }, { name: "device_session_id", label: "Device Session ID", type: "uuid" }, { name: "gate", label: "Gate", type: "text" }, { name: "notes", label: "Notes", type: "text" }],
  },
  {
    key: "tapband-telemetry-events",
    label: "TapBand Telemetry",
    table: "tapband_telemetry_events",
    primaryKey: "id",
    description: "Review privacy-minimised TapBand lifecycle, reader and credential telemetry.",
    orderBy: "occurred_at",
    listColumns: ["event_type", "severity", "outcome", "occurred_at"],
    fields: [idField, { name: "event_type", label: "Event Type", type: "text", readonly: true }, { name: "severity", label: "Severity", type: "select", options: ["info", "warning", "critical"], readonly: true }, { name: "outcome", label: "Outcome", type: "text", readonly: true }, { name: "org_id", label: "Organization ID", type: "uuid", readonly: true }, { name: "event_id", label: "Event ID", type: "uuid", readonly: true }, { name: "device_id", label: "Device ID", type: "uuid", readonly: true }, { name: "channel", label: "Channel", type: "text", readonly: true }, { name: "credential_hash", label: "Credential Hash", type: "text", readonly: true }, { name: "serial_hash", label: "Serial Hash", type: "text", readonly: true }, { name: "actor_hash", label: "Actor Hash", type: "text", readonly: true }, { name: "reader_id", label: "Reader ID", type: "text", readonly: true }, { name: "correlation_id", label: "Correlation ID", type: "text", readonly: true }, { name: "latency_ms", label: "Latency MS", type: "number", readonly: true }, { name: "metadata", label: "Metadata JSON", type: "json", readonly: true }, { name: "occurred_at", label: "Occurred At", type: "datetime", readonly: true }, { name: "ingested_at", label: "Ingested At", type: "datetime", readonly: true }],
  },
  {
    key: "tapband-alerts",
    label: "TapBand Alerts",
    table: "tapband_alerts",
    primaryKey: "id",
    description: "Review TapBand fraud, reader-health and operational alert records.",
    orderBy: "last_seen_at",
    listColumns: ["alert_key", "severity", "status", "last_seen_at"],
    fields: [idField, { name: "alert_key", label: "Alert Key", type: "text", readonly: true }, { name: "severity", label: "Severity", type: "select", options: ["warning", "critical"], readonly: true }, { name: "status", label: "Status", type: "select", options: ["open", "acknowledged", "resolved"] }, { name: "org_id", label: "Organization ID", type: "uuid", readonly: true }, { name: "event_id", label: "Event ID", type: "uuid", readonly: true }, { name: "device_id", label: "Device ID", type: "uuid", readonly: true }, { name: "correlation_id", label: "Correlation ID", type: "text", readonly: true }, { name: "title", label: "Title", type: "text", readonly: true }, { name: "message", label: "Message", type: "text", readonly: true }, { name: "details", label: "Details JSON", type: "json", readonly: true }, { name: "first_seen_at", label: "First Seen At", type: "datetime", readonly: true }, { name: "last_seen_at", label: "Last Seen At", type: "datetime", readonly: true }, { name: "resolved_at", label: "Resolved At", type: "datetime" }],
  },
  {
    key: "tapband-feature-configs",
    label: "TapBand Feature Configs",
    table: "tapband_feature_configs",
    primaryKey: "id",
    description: "Configure environment, organization and event-scoped TapBand capabilities.",
    orderBy: "updated_at",
    listColumns: ["environment", "org_id", "event_id", "outlet_id", "enabled"],
    fields: [idField, { name: "environment", label: "Environment", type: "select", options: ["production", "preview", "development", "all"], required: true }, { name: "org_id", label: "Organization ID", type: "uuid" }, { name: "event_id", label: "Event ID", type: "uuid" }, { name: "outlet_id", label: "Outlet ID", type: "text" }, { name: "enabled", label: "Enabled", type: "boolean" }, { name: "product_visibility_enabled", label: "Product Visibility", type: "boolean" }, { name: "credential_lookup_enabled", label: "Credential Lookup", type: "boolean" }, { name: "provisioning_enabled", label: "Provisioning", type: "boolean" }, { name: "activation_enabled", label: "Activation", type: "boolean" }, { name: "outlet_lookup_enabled", label: "Outlet Lookup", type: "boolean" }, { name: "outlet_sales_enabled", label: "Outlet Sales", type: "boolean" }, { name: "online_nfc_scanning_enabled", label: "Online NFC Scanning", type: "boolean" }, { name: "offline_nfc_scanning_enabled", label: "Offline NFC Scanning", type: "boolean" }, { name: "offline_manifest_issuance_enabled", label: "Offline Manifest Issuance", type: "boolean" }, { name: "qr_fallback_enabled", label: "QR Fallback", type: "boolean" }, { name: "lost_replacement_enabled", label: "Lost Replacement", type: "boolean" }, { name: "desfire_secure_mode_enabled", label: "DESFire Secure Mode", type: "boolean" }, { name: "allowed_chip_families", label: "Allowed Chip Families JSON", type: "json", placeholder: "[\"DESFire EV3\"]" }, { name: "allowed_key_versions", label: "Allowed Key Versions JSON", type: "json", placeholder: "[\"kv1\"]" }, { name: "supported_entry_zones", label: "Supported Entry Zones JSON", type: "json", placeholder: "[\"gate-a\"]" }, { name: "manifest_validity_seconds", label: "Manifest Validity Seconds", type: "number" }, { name: "tap_debounce_ms", label: "Tap Debounce MS", type: "number" }, { name: "outlet_verification_requirement", label: "Outlet Verification", type: "select", options: ["none", "staff_pin", "phone_otp", "identity_review"] }, { name: "replacement_fee_cents", label: "Replacement Fee Cents", type: "number" }, { name: "replacement_fee_waiver_enabled", label: "Replacement Fee Waiver", type: "boolean" }, { name: "effective_within_seconds", label: "Effective Within Seconds", type: "number" }, { name: "public_client_config", label: "Public Client Config JSON", type: "json", placeholder: "{}" }, { name: "notes", label: "Notes", type: "text" }, { name: "created_by", label: "Created By", type: "readonly", readonly: true }, { name: "updated_by", label: "Updated By", type: "readonly", readonly: true }, createdAtField, { name: "updated_at", label: "Updated At", type: "readonly", readonly: true }],
  },
  {
    key: "tapband-kill-switches",
    label: "TapBand Kill Switches",
    table: "tapband_kill_switches",
    primaryKey: "id",
    description: "Rapidly disable TapBand capabilities, batches, chip/key versions, outlets or devices.",
    orderBy: "created_at",
    listColumns: ["switch_type", "environment", "enabled", "reason_code"],
    fields: [idField, { name: "switch_type", label: "Switch Type", type: "select", options: ["all_credential_lookups", "supplier_batch", "chip_family", "key_version", "outlet", "provisioning_device", "nfc_scanning", "offline_manifest_issuance", "customer_replacement"], required: true }, { name: "environment", label: "Environment", type: "select", options: ["production", "preview", "development", "all"], required: true }, { name: "org_id", label: "Organization ID", type: "uuid" }, { name: "event_id", label: "Event ID", type: "uuid" }, { name: "target_ref", label: "Target Reference", type: "text" }, { name: "capability", label: "Capability", type: "select", options: ["", "product_visibility", "credential_lookup", "credential_provisioning", "customer_activation", "outlet_identity_lookup", "outlet_ticket_assignment", "online_nfc_scanning", "offline_nfc_scanning", "offline_manifest_issuance", "qr_fallback", "lost_replacement", "desfire_secure_mode"] }, { name: "reason_code", label: "Reason Code", type: "text", required: true, placeholder: "tapband_nfc_disabled_by_ops" }, { name: "reason", label: "Reason", type: "text", required: true }, { name: "enabled", label: "Enabled", type: "boolean" }, { name: "starts_at", label: "Starts At", type: "datetime" }, { name: "ends_at", label: "Ends At", type: "datetime" }, { name: "created_by", label: "Created By", type: "readonly", readonly: true }, { name: "revoked_by", label: "Revoked By", type: "uuid" }, { name: "revoked_at", label: "Revoked At", type: "datetime" }, createdAtField],
  },
  {
    key: "feature-flags",
    label: "Feature Flags",
    table: "feature_flags",
    primaryKey: "id",
    description: "Enable beta or premium features per organization.",
    orderBy: "created_at",
    listColumns: ["key", "enabled", "created_at"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "key", label: "Key", type: "text", required: true }, { name: "enabled", label: "Enabled", type: "boolean" }, { name: "config", label: "Config JSON", type: "json", placeholder: "{}" }],
  },
  {
    key: "price-rules",
    label: "Price Rules",
    table: "price_rules",
    primaryKey: "id",
    description: "Configure promo codes, fees, discounts and taxes.",
    orderBy: "created_at",
    listColumns: ["code", "type", "value_numeric", "is_active"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid", required: true }, { name: "event_id", label: "Event ID", type: "uuid" }, { name: "ticket_type_id", label: "Ticket Type ID", type: "uuid" }, { name: "code", label: "Code", type: "text" }, { name: "type", label: "Type", type: "select", options: ["absolute_discount", "percent_discount", "abs_fee", "percent_fee", "tax"], required: true }, { name: "value_numeric", label: "Value", type: "number", required: true }, { name: "applies_to", label: "Applies To", type: "select", options: ["item", "order"], required: true }, { name: "starts_at", label: "Starts At", type: "datetime" }, { name: "ends_at", label: "Ends At", type: "datetime" }, { name: "max_redemptions", label: "Max Redemptions", type: "number" }, { name: "per_user_limit", label: "Per User Limit", type: "number" }, { name: "is_active", label: "Active", type: "boolean" }],
  },
  {
    key: "price-rule-redemptions",
    label: "Price Rule Redemptions",
    table: "price_rule_redemptions",
    primaryKey: "id",
    description: "Review promo code and discount redemptions.",
    orderBy: "redeemed_at",
    listColumns: ["price_rule_id", "user_id", "order_id", "redeemed_at"],
    fields: [idField, { name: "price_rule_id", label: "Price Rule ID", type: "uuid", required: true }, { name: "user_id", label: "User ID", type: "uuid" }, { name: "order_id", label: "Order ID", type: "uuid" }, { name: "redeemed_at", label: "Redeemed At", type: "datetime" }],
  },
  {
    key: "webhooks",
    label: "Webhooks",
    table: "webhooks",
    primaryKey: "id",
    description: "Review provider webhook receipts and processing status.",
    orderBy: "received_at",
    listColumns: ["provider", "provider_event_id", "received_at", "processed_at"],
    fields: [idField, { name: "provider", label: "Provider", type: "text", required: true }, { name: "signature", label: "Signature", type: "text" }, { name: "provider_event_id", label: "Provider Event ID", type: "text" }, { name: "payload", label: "Payload JSON", type: "json", required: true }, { name: "processed_at", label: "Processed At", type: "datetime" }],
  },
  {
    key: "jobs",
    label: "Jobs",
    table: "jobs",
    primaryKey: "id",
    description: "Monitor background jobs, retry attempts and failures.",
    orderBy: "created_at",
    listColumns: ["kind", "attempts", "max_attempts", "last_error"],
    fields: [idField, { name: "kind", label: "Kind", type: "text", required: true }, { name: "payload", label: "Payload JSON", type: "json", required: true }, { name: "run_after", label: "Run After", type: "datetime" }, { name: "attempts", label: "Attempts", type: "number" }, { name: "max_attempts", label: "Max Attempts", type: "number" }, { name: "last_error", label: "Last Error", type: "text" }, { name: "locked_at", label: "Locked At", type: "datetime" }],
  },
  {
    key: "audit-log",
    label: "Audit Log",
    table: "audit_log",
    primaryKey: "id",
    description: "Review organization action audit entries.",
    orderBy: "created_at",
    listColumns: ["table_name", "action", "actor_id", "created_at"],
    fields: [idField, { name: "org_id", label: "Organization ID", type: "uuid" }, { name: "actor_id", label: "Actor ID", type: "uuid" }, { name: "table_name", label: "Table Name", type: "text", required: true }, { name: "record_id", label: "Record ID", type: "text" }, { name: "action", label: "Action", type: "select", options: ["insert", "update", "delete", "login", "logout", "other"], required: true }, { name: "changes", label: "Changes JSON", type: "json" }, { name: "ip", label: "IP", type: "text" }, { name: "user_agent", label: "User Agent", type: "text" }],
  },
  {
    key: "app-audit-log",
    label: "App Audit Log",
    table: "app_audit_log",
    primaryKey: "id",
    description: "Review application-level row change records.",
    orderBy: "occurred_at",
    listColumns: ["schema_name", "table_name", "operation", "occurred_at"],
    fields: [idField, { name: "schema_name", label: "Schema Name", type: "text", required: true }, { name: "table_name", label: "Table Name", type: "text", required: true }, { name: "operation", label: "Operation", type: "text", required: true }, { name: "row_data", label: "Row Data JSON", type: "json" }, { name: "changed_by", label: "Changed By", type: "uuid" }, { name: "change_query", label: "Change Query", type: "text" }],
  },
  {
    key: "admin-users",
    label: "Admin Users",
    table: "admin_users",
    primaryKey: "user_id",
    description: "Manage elevated platform admin allowlist records.",
    orderBy: "created_at",
    listColumns: ["user_id", "created_at"],
    fields: [{ name: "user_id", label: "User ID", type: "uuid", required: true }, createdAtField],
  },
]

export function getAdminResource(key: string) {
  return ADMIN_RESOURCES.find((resource) => resource.key === key)
}

export function getAdminResources(keys: string[]) {
  return keys.map((key) => getAdminResource(key)).filter(Boolean) as AdminResource[]
}
