-- TICK-408: make shared-UAT teardown remove all rows owned by fixture orgs.
--
-- Browser checkout creates orders with generated IDs. The previous teardown only
-- deleted a fixed list of seed order IDs, leaving browser-created orders behind.
-- A later seed then failed when teardown tried to delete the fixture organization
-- through the restrictive orders_org_id_fkey.

create or replace function public.fn_teardown_uat_fixtures()
  returns jsonb
  language plpgsql
  security definer
  set search_path to 'public'
as $$
declare
  v_orgs uuid[] := array[
    'da7a0000-0000-4000-8000-000000000001'::uuid,
    'da7a0000-0000-4000-8000-000000000002'::uuid
  ];
  v_users uuid[] := array[
    'da7a0001-0000-4000-8000-000000000001'::uuid,
    'da7a0001-0000-4000-8000-000000000002'::uuid,
    'da7a0001-0000-4000-8000-000000000003'::uuid,
    'da7a0001-0000-4000-8000-000000000004'::uuid,
    'da7a0001-0000-4000-8000-000000000005'::uuid,
    'da7a0001-0000-4000-8000-000000000006'::uuid,
    'da7a0001-0000-4000-8000-000000000007'::uuid,
    'da7a0001-0000-4000-8000-000000000008'::uuid
  ];
  v_venue uuid := 'da7a0002-0000-4000-8000-000000000001';
  v_orders integer;
begin
  select count(*) into v_orders from public.orders where org_id = any(v_orgs);

  delete from public.scans s
   where s.event_id in (select id from public.events where org_id = any(v_orgs));
  delete from public.ledger_entries where org_id = any(v_orgs);
  delete from public.refund_items ri
   where ri.refund_id in (
     select r.id from public.refunds r
     join public.payments p on p.id = r.payment_id
     where p.order_id in (select id from public.orders where org_id = any(v_orgs))
   );
  delete from public.refunds r
   where r.payment_id in (
     select p.id from public.payments p
     where p.order_id in (select id from public.orders where org_id = any(v_orgs))
   );
  delete from public.payment_outbox
   where order_id in (select id from public.orders where org_id = any(v_orgs));
  delete from public.payment_attempts
   where order_id in (select id from public.orders where org_id = any(v_orgs));
  delete from public.payments
   where order_id in (select id from public.orders where org_id = any(v_orgs));
  -- Unlike the other direct order children, this FK has no ON DELETE action.
  delete from public.price_rule_redemptions
   where order_id in (select id from public.orders where org_id = any(v_orgs));
  delete from public.order_items
   where order_id in (select id from public.orders where org_id = any(v_orgs));

  -- This predicate intentionally targets every fixture-org order, including IDs
  -- generated by browser checkout rather than only deterministic seed IDs.
  delete from public.orders where org_id = any(v_orgs);

  delete from public.payouts where org_id = any(v_orgs);
  delete from public.payout_accounts where org_id = any(v_orgs);
  delete from public.devices where org_id = any(v_orgs);
  delete from public.seat_holds
   where event_id in (select id from public.events where org_id = any(v_orgs));
  delete from public.ticket_types
   where event_id in (select id from public.events where org_id = any(v_orgs));
  delete from public.events
   where org_id = any(v_orgs) or venue_id = v_venue;
  delete from public.pricing_plans where org_id = any(v_orgs);
  delete from public.org_members where org_id = any(v_orgs);
  delete from public.organizations where id = any(v_orgs);
  delete from public.venues where id = v_venue;
  delete from public.notifications where user_id = any(v_users);
  delete from public.profiles where user_id = any(v_users);
  delete from auth.users where id = any(v_users);

  return jsonb_build_object(
    'ok', true,
    'removed', jsonb_build_object('orders_removed', v_orders)
  );
end;
$$;

grant execute on function public.fn_teardown_uat_fixtures() to service_role;
revoke execute on function public.fn_teardown_uat_fixtures() from public, anon, authenticated;
